### PR TITLE
469 fix: node resource usage percentage

### LINKED ISSUE #469: [Bug]: Node page and Node details don’t sync.
## Describe the bug

As title.

## Version

3.0.0-RC1

## To Reproduce

N/A

## Expected behavior

Node page and Node details must be sync.

## Screenshots

Image

Image

Image

Image

##Additional context

N/A

### PR DESCRIPTION
**Pull request by steven-chiu-bigstack**
#### What type of PR is this?

fix

#### What this PR does / why we need it

- Adjust Node tables and Node Detail resource usage percentage source (use the percentage returned by the API instead of calculating it in the frontend).
- Enhancement:Show at least 1% in CosProgessBar when progress > 0.

   image

   - Before

      image

   - After

      image

#### Which issue(s) this PR fixes

Close bigstack-oss/cubecos#112

### CODE REVIEW

File: packages/cube-frontend-web-app/src/pages/home/overview/_components/NodePanel/NodeTable.tsx [hunk 1]
```diff
@@ -76,7 +75,7 @@ export const NodeTable = (props: NodeTableProps) => {
         {(cpu) => (
           <CosProgressBar
             className="min-w-[90px]"
-            progress={toPercentage(cpu.usedCores, cpu.totalCores)}
+            progress={Math.floor(cpu.usedPercent)}
```
Comment (raven-pan) [inline packages/cube-frontend-web-app/src/pages/home/overview/_components/NodePanel/NodeTable.tsx]: Discussion:
It seems that we already round the percentage in `CosProgressBar`.
Do we still need to use `Math.floor`?

**Review by raven-pan — APPROVED** [review]

File: packages/cube-frontend-web-app/src/pages/home/overview/_components/NodePanel/NodeTable.tsx (hunk 1 above)
Comment (steven-chiu-bigstack) [reply packages/cube-frontend-web-app/src/pages/home/overview/_components/NodePanel/NodeTable.tsx]: From what the API response shows, it appears to be the opposite: 🤔 

```json
{
  "id": "control-10.32.45.10-g2u1bojz-3cf9fb8b-4f0b-4454-ad5f-1fe2e6a9c776",
  "dataCenter": "control",
  "hostname": "cube453",
  "vcpu": {
    "totalCores": 48,
    "usedCores": 3.2082,
    "usedPercent": 4.0067,
    "freeCores": 44.7917,
    "freePercent": 95.9932
  },
  "memory": {
    "totalMiB": 128797.0273,
    "usedMiB": 32130.4062,
    "usedPercent": 24.9465,
    "freeMiB": 96666.621,
    "freePercent": 75.0534
  },
  "storage": {
    "totalMiB": 201275.8632,
    "usedMiB": 39799.8085,
    "usedPercent": 20.8397,
    "freeMiB": 151180.6562,
    "freePercent": 79.1603
  },
}
```

Or has the API been adjusted lately?

Comment (steven-chiu-bigstack) [reply packages/cube-frontend-web-app/src/pages/home/overview/_components/NodePanel/NodeTable.tsx]: Sorry, I misread your comment. You're right, we don't have to `Math.floor` here.
Let me fix this now, thanks for pointing it out! 🙏 🙇‍♂️

Comment (steven-chiu-bigstack) [reply packages/cube-frontend-web-app/src/pages/home/overview/_components/NodePanel/NodeTable.tsx]: FIxed, looks good:

image

image

image
