### PR TITLE
341 fix(web-app): home chart page usage panel role groups

### LINKED ISSUE #341: [Bug]: Roles should only display cloud or/ edge nodes at a time
## Describe the bug

 Roles should only display cloud or/ edge nodes

1. Home 上方圖表
2. Home chart
3. Nodes nodes roles Dropdown 

## To Reproduce

1. Go to 'Home 上方圖表'/ 'Home chart'/ 'Nodes nodes roles Dropdown ''

## Expected behavior

Roles should only display cloud or/ edge nodes

## Screenshots

##Additional context

### PR DESCRIPTION
**Pull request by steven-chiu-bigstack**
#### What type of PR is this?

Fix

#### What this PR does / why we need it

In Home Chart page -> Usage panel, show role groups based on the data center type.

#### Which issue(s) this PR fixes

Close #341 

- Cloud
  - image
- Edge
  - image

### CODE REVIEW

File: packages/cube-frontend-web-app/src/pages/home/chart/_components/UsagePanel/usagePanelUtils.ts [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+  dataCenterType: GetDataCentersResponseDataInnerTypeEnum,
+): RoleGroup[] => {
+  const mapFns: Record<
+    GetDataCentersResponseDataInnerTypeEnum,
+    (metrics: GetMetricsResponseData) => RoleGroup[]
+  > = {
+    cloud: mapCloudRoleGroups,
+    edge: mapEdgeRoleGroups,
+  }
+  const fn = mapFns[dataCenterType]
```
Comment (steven-chiu-bigstack) [inline packages/cube-frontend-web-app/src/pages/home/chart/_components/UsagePanel/usagePanelUtils.ts:23]: I chose to define mapping functions based on data center type instead of just role name because there's a specific order of how role groups should be displayed.

**Review by raven-pan — APPROVED** [review]
LGTM!
