### PR TITLE
fix: 375 the import license modal missing the feature field

### LINKED ISSUE #45: UI Library - Table Details
[Mockup](https://www.figma.com/design/T95ymFSTSDKdmr9WEjylQE/COS-Design-System-2024?node-id=82-2736&m=dev)

Dependencies:

- #43

### LINKED ISSUE #375: [Bug]: The Import License Modal missing the feature field
## Describe the bug

The Import License Modal missing the feature field.

## Version

CUBE_3.0.0_20250508-1907_e3c2bbd

## To Reproduce

1. Go to `Maintenace/License` Page
2. Click the `Import License` button and upload your testing license file.

## Expected behavior

The Import License Modal should display product feature field.

## Screenshots

Actual:

Image

Expected:

Image

### PR DESCRIPTION
**Pull request by raven-pan**
#### What type of PR is this?

Fix

#### Which issue(s) this PR fixes

Fixes #375
Close #45 

#### Screenshots

Screenshot 2025-05-13 at 4 48 44 PM

### CODE REVIEW

**Review by steven-chiu-bigstack — APPROVED** [review]
LGTM!

File: packages/cube-frontend-web-app/src/pages/maintenance/license/_components/LicenseActions/ImportLicenseModal/ImportLicenseTable.tsx [hunk 1]
```diff
@@ -19,6 +19,7 @@ export const ImportLicenseTable = (props: ImportLicenseTableProps) => {
   const licenseDetailsRows = [
     { key: 'Product', value: license.product.name },
     { key: 'Status', value: license.status.current },
+    { key: 'Feature', value: license.product.feature },
```
Comment (steven-chiu-bigstack) [inline packages/cube-frontend-web-app/src/pages/maintenance/license/_components/LicenseActions/ImportLicenseModal/ImportLicenseTable.tsx]: Sorry, it seems that we're using `capitalize(license.product.feature)` in other places. It's probably better to align the behaviors.

By the way, the table header seems to be missing.

- It looks like the root cause is because license name is not returned by the API.
- Do you think it's necessary to implement the [Table - Details](https://www.figma.com/design/T95ymFSTSDKdmr9WEjylQE/COS-Design-System-2024?node-id=82-2736&t=BUt7b1ZeI7VrhOPk-0) component at the current stage? If not, we can just skip this part and merge this PR. 🙏 

{3BC54323-DA96-402C-BEA3-792E574626FE}

Comment (steven-chiu-bigstack) [reply packages/cube-frontend-web-app/src/pages/maintenance/license/_components/LicenseActions/ImportLicenseModal/ImportLicenseTable.tsx]: Update:

I proceed to implement the Table - Details component in this PR and use it in `ImportLicenseTable`:

- Story
   chrome_MByyxJBliD
- ImportLicenseTable
   chrome_v4GxwG4ERO

One thing worth mentioning is that I set a default value `Unnamed License` for the table header so that it doesn't look strange when the license name is empty for whatever reason.

Let me know if you have any concerns, thanks! 🙏
