### PR TITLE
179 unable to logout when two browser windows are open

### LINKED ISSUE #179: Unable to Logout when two browser windows are open
---
name: Unable to Logout when two browser windows are open
about: 
title: '[Bug]: '
labels: 'bug'
assignees: ''

---

## Describe the bug

When logged in to more than two browser windows simultaneously, pressing the logout button has no effect. After refreshing, the user remains logged in.

## Version 

Release: cube-cos-ui - ad9cc96

## To Reproduce

1. open two browser to login
2. press logout button
3. no effect
4. two browser after refreshing still remains logged in

## Expected behavior

When the logout button is pressed in one browser, it logout, and the other browser will either automatically logout or show the logged-out status after a refresh.

## Screenshots

Image

https://github.com/user-attachments/assets/a6bbea37-f755-4502-b75d-112e59437965

### PR DESCRIPTION
**Pull request by steven-chiu-bigstack**
#### What type of PR is this?

Fix

#### What this PR does / why we need it

Fix unable to logout when two (or more) COS windows are opened bug.

#### Which issue(s) this PR fixes

Fixes #179 

#### Special notes for your reviewer

In short, I replace all `useCosStreamRequest` with `useCosGetRequest` + `useSequentialInterval` for polling. 

- Single request:

https://github.com/user-attachments/assets/4120fb86-41b5-4cb2-b85d-a0fa86aa8138

- Multiple requests:
 
https://github.com/user-attachments/assets/81a64e45-252f-4a0c-8f88-1251d133f772

### CODE REVIEW

File: packages/cube-frontend-web-app/src/pages/home/overview/_components/HealthPanel/HealthPanel.tsx [hunk 1]
```diff
@@ -61,12 +68,14 @@ const HealthPanel = () => {
...
-        isRepairButtonLoading={isRepairButtonLoading}
-      />
+      {(isLoading || errorServices.length > 0) && (
+        <HealthError
+          isLoading={isLoading}
+          errorServices={errorServices}
+          onRepair={handleRepair}
+          isRepairButtonLoading={isRepairButtonLoading}
+        />
+      )}
```
Comment (steven-chiu-bigstack) [inline packages/cube-frontend-web-app/src/pages/home/overview/_components/HealthPanel/HealthPanel.tsx:80]: Added a check to only show `HealthError` when there are errors:

image

**Review by raven-pan — APPROVED** [review]
LGTM, Thanks for your help in solving this issue!

I noticed that the current `useInterval` strategy results in a lot of pending requests.

We can handle this in issue https://github.com/bigstack-oss/cube-cos-ui/issues/189.

https://github.com/user-attachments/assets/8146a4e6-4586-4da2-9891-5a49e4ff6135

**Comment by steven-chiu-bigstack** [comment]
Hi @raven-pan 

Thanks for pointing out the pending requests problem! I've updated the PR that introduced the `useSequentialInterval` hook and replaced all the polling `useInterval` with it.
Please have a second look when you have time, thank you! 🙏
