### PR TITLE
fix: events chart chart page issues

### LINKED ISSUE #233: Page - Display data from the API on `Event Chart` page
1. Replace `rankedEvents` with `rankedEvents` from useRankedEvents in `EventsChartComparison` and `EventsChartProportion`.
2. Need to add chart display mode without data

### LINKED ISSUE #255: [Issue]: Add an 'All' option to the filter
## Describe the issue

[10.150](https://10.32.10.150:4443/)
An 'All' option should be added to the filter to allow the status to return to its initial state.

Image

## Version

CUBE_3.0.0_20250414-1327_fa8abf5

## To Reproduce

1. Go to Events Chart page
2. Click each filter

## Expected behavior

Each filter should have an option to restore its initial state.

### LINKED ISSUE #262: Page - Record the time range in the URL query on the Events Chart page
1. The time range needs to be recorded in the URL to maintain consistency of the filter behaviour.
2. The time range recorded in the URL will become the default selection and will persist even after navigating between pages.

### PR DESCRIPTION
**Pull request by lizzy-liang-bigstack**
#### What type of PR is this?

- Feature
- Fix

##### 1) Display data from the API on `Events Chart` page ➡️ commit [4292623](https://github.com/bigstack-oss/cube-cos-ui/pull/263/commits/4292623f8bee09e93f2dc7859197f0628329934b)
- Remove `mockData`
- Apply `No Data` status to Charts

https://github.com/user-attachments/assets/08104f93-060e-4526-b3a5-a372b0c7257d

##### 2) Add an 'All' option to the filter ➡️ commit [40d1bb1](https://github.com/bigstack-oss/cube-cos-ui/pull/263/commits/40d1bb131247917b63824cd3a86bacad156e68a8)

https://github.com/user-attachments/assets/64e2940f-d6ad-477f-85db-0dd7163570ae

##### 3) Record the time range in the URL query on the `Events Chart` page ➡️ [88b3985](https://github.com/bigstack-oss/cube-cos-ui/pull/263/commits/88b39850db197b7eba48a0dc5699ea446e9d4540)

https://github.com/user-attachments/assets/f414daf7-cf62-4fb3-b60b-315a8d35dc92

#### Which issue(s) this PR fixes

Fixes #233 ➡️ commit [4292623](https://github.com/bigstack-oss/cube-cos-ui/pull/263/commits/4292623f8bee09e93f2dc7859197f0628329934b)

Fixes #255 ➡️ commit [40d1bb1](https://github.com/bigstack-oss/cube-cos-ui/pull/263/commits/40d1bb131247917b63824cd3a86bacad156e68a8)

Fixes #262 ➡️ commit [88b3985](https://github.com/bigstack-oss/cube-cos-ui/pull/263/commits/88b39850db197b7eba48a0dc5699ea446e9d4540)

#### Special notes for your reviewer

> Note

#### Additional documentation

```docs

```

### CODE REVIEW

File: packages/cube-frontend-web-app/src/pages/events/chart/_components/useEventsChartQuery.ts [hunk 1]
```diff
@@ -1,117 +1,103 @@
...
+  ) => void
 }
 
 export const useEventsChartQuery = (): UseEventsChartQuery => {
   const [searchParams, setSearchParams] = useSearchParams()
 
-  const [eventsType, setEventsType] = useState<GetEventsTypeEnum>(
-    getValidEventsType(searchParams),
+  const [chartQuery, setChartQuery] = useState<ChartQuery>(
+    initChartQuery(searchParams),
```
Comment (steven-chiu-bigstack) [inline packages/cube-frontend-web-app/src/pages/events/chart/_components/useEventsChartQuery.ts:53]: Nitpick: In JSX, functions like this will be executed in every render. Since `initChartQuery` is used to initialize the `chartQuery`, it'd be great if `initChartQuery` is run only once.

To do this, we can pass a function with no arguments to `useState` ([docs](https://react.dev/reference/react/useState#parameters)). In short, this is more efficient:

```tsx
const [chartQuery, setChartQuery] = useState<ChartQuery>(
  () => initChartQuery(searchParams)
)
```

File: packages/cube-frontend-web-app/src/pages/events/chart/EventsChartPage.tsx [hunk 2]
```diff
@@ -5,34 +5,55 @@ import { useTimeRange } from '@cube-frontend/web-app/components/TimeRangeDropdow
...
+  const {
+    timeRanges,
+    timeRange,
+    onTimeRangeChange: onTimeRangeDropdownChange,
+  } = useTimeRange({
+    includes: chartTimeRanges,
+    defaultValue: chartQuery.past,
   })
 
   const { isEventsFilterLoading, getEventsFilter } = useEventsFilter()
```
Comment (steven-chiu-bigstack) [inline packages/cube-frontend-web-app/src/pages/events/chart/EventsChartPage.tsx]: Nitpick: Regarding the `useEventsFilter` hook, we can just return `eventsFilter: data?.[type]` instead of the `getEventsFilter` function:

{4D191FEB-8E82-4FE1-8891-8EE7A163AF2D}

File: packages/cube-frontend-web-app/src/pages/events/chart/_components/utils.ts [hunk 3]
```diff
@@ -1,42 +1,165 @@
...
-  categories: 'category',
-  ids: 'id',
-  names: 'name',
+const getQueryValue = (
+  chartType: ChartType,
+  queryKey: keyof EventsApiGetRankedEventsRequest,
+  chartQuery: ChartQuery,
+) => {
+  const dynamicKey =
+    `${chartType}${queryKey.charAt(0).toUpperCase()}${queryKey.slice(1)}` as keyof ChartQuery
```
Comment (steven-chiu-bigstack) [inline packages/cube-frontend-web-app/src/pages/events/chart/_components/utils.ts]: Nitpick: We can utilize the [upperFirst](https://lodash.com/docs/4.17.15#upperFirst) function from Lodash to simplify `${queryKey.charAt(0).toUpperCase()}${queryKey.slice(1)}`.

```ts
const dynamicKey =`${chartType}${upperFirst(queryKey)}` as keyof ChartQuery
```

File: packages/cube-frontend-web-app/src/pages/events/chart/_components/utils.ts [hunk 4]
```diff
@@ -1,42 +1,165 @@
...
+  eventId: string,
+): string => {
+  const { type, past, category, severity, host, instance } =
+    getRequestQueryByChartType(chartType, chartQuery)
 
-  if (!dropdownFilterKey) {
-    console.warn('Not a valid filter key')
-  }
+  const endDate = dayjs()
+  const startDate = endDate.subtract(timeRangeToDaysMapping[past!], 'day')
```
Comment (steven-chiu-bigstack) [inline packages/cube-frontend-web-app/src/pages/events/chart/_components/utils.ts]: Should we also do `endDate.subtract(1, 'hour')` when `past` is `1h`? If yes, I think there's a chance we can reuse the `timeRangeDelta` object from `cube-frontend-web-app/src/hooks/useTimeFrame/timeFrameUtils.ts`:

{F36ED7B6-1E9B-46C0-AFD1-E123319EBE5F}

Since the values in `timeRangeDelta` is negative, make sure to call `endDate.add()` instead of `endDate.subtract()`.

File: packages/cube-frontend-web-app/src/pages/events/chart/_components/timeRangeUtils.ts [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+  '14d',
+] as const satisfies TimeRange[]
+
+export type ChartTimeRanges = (typeof chartTimeRanges)[number]
+
+export const DEFAULT_TIME_RANGE = '24h' satisfies ChartTimeRanges
+
+export const timeRangeToDaysMapping: Record<ChartTimeRanges, number> = {
+  '1h': 0,
+  '24h': 0,
```
Comment (steven-chiu-bigstack) [inline packages/cube-frontend-web-app/src/pages/events/chart/_components/timeRangeUtils.ts]: It looks like the value for `24h` should be `1` (day).

**Review by steven-chiu-bigstack — APPROVED** [review]
Hi @lizzy-liang-bigstack 

Looks good, nice work! 👍 
Just left some comments for you to check.

File: packages/cube-frontend-web-app/src/pages/events/chart/_components/utils.ts (hunk 4 above)
Comment (lizzy-liang-bigstack) [reply packages/cube-frontend-web-app/src/pages/events/chart/_components/utils.ts]: Ah, that's a good point — reusing `timeRangeDelta` would make the function simpler.
Thank you for pointing it out!

File: packages/cube-frontend-web-app/src/pages/events/chart/_components/timeRangeUtils.ts (hunk 5 above)
Comment (lizzy-liang-bigstack) [reply packages/cube-frontend-web-app/src/pages/events/chart/_components/timeRangeUtils.ts]: I'll replace the mapping with `timeRangeDelta` since it would be more accurate as mentioned above. Thank you :)
