### PR TITLE
feat: 143 574 repair logs fixing time range and select visible part

### LINKED ISSUE #143: Page - Health Overview and Health Detail Page Health Segmented Bar Rects Hardly Visible In Large Time Range
Segment rects becomes hardly visible in large time range, making them difficult to interact with:

https://github.com/user-attachments/assets/4a241f13-e5f9-4970-88aa-2930efcf9d05

Discuss with the designers and see how we can address this issue.

### LINKED ISSUE #574: [Feature] Health UI displays repair logs and fixing time range.
Image

1. Display yellow/orange time ranges on health time bar.
2. Currently, the health details table displays aggregated health events. We should display the original health events in the health details table. 
3. Show host name in the health details table, since we at least have 3 nodes (3 control-converged), we want to easily identify which node the  events occurred on.

Figma: https://www.figma.com/design/kSUzxXJ3OZ5RXSZCRjZ9o1/COS-3.1-M2-UI-mockup?node-id=12064-22580&m=dev

### PR DESCRIPTION
**Pull request by raven-pan**
⚠️ This PR is based on [the Node Device PR](https://github.com/bigstack-oss/cube-cos-ui/pull/542), as we need to apply the latest `cube-cos-openapi` SDK to resolve Typescript type errors and  to make the CI pass.

#### What type of PR is this?

Feat

#### What this PR does / why we need it

1.) The health details table displays `raw` health events, and health time bar displays `aggregated` events.
2.) The health details table contains `fix related events`, and the health time bar displays `FIXING` time ranges.
3.) Add `NG` and `FIXING` indicators on bottom health time bar.
4.) Add a `brush` filter on bottom health time bar, allows the users to select specified time range and zoom in on top health time bar.
5.) Optimize the x-axis display by using the [d3.js ticks](https://d3js.org/d3-scale/time#time_ticks) and defining `PIXEL_PER_TICK` to make it more responsive and readable.

https://github.com/user-attachments/assets/f8bcb1ed-0c51-4cbb-886a-0fdd842dafcd

#### Which issue(s) this PR fixes

- Fixes #143 
- Fixes #574 

#### OpenAPI

The health history was aggregated by time(10 minutes) and status(fixing related status > ng related status > ok related status). please see the `aggregate` params in the `cube-cos-openapi`:

Screenshot 2025-07-18 at 9 00 13 PM

The `cube-cos-openapi` commit: https://github.com/bigstack-oss/cube-cos-openapi/pull/49/commits/cfdcdcc09041d17e34546e4f581192f557b505cf

#### Why we need to aggregate health events

1. Since we only store health events in `InfluxDB`, it's difficult to observe the system status on the time bar chart. Therefore, we convert these health event points to health status ranges.
2. Since we have a least 3 hosts (3cc), if cc1 is NG at 15:00:00 but cc2, cc3 is OK in 15:00:01, and we don't aggregate these health events , the health time bar will display only 1 second of NG, which is not reasonable.

#### How to check raw data

1. ssh to a cube host.
2. run `influx`
3. run `use events`
4. run `SELECT * FROM health LIMIT 20`

image

#### D3.js

1. Add `d3.js` package to help developers draw SVG charts.
2. Customize [d3-brush](https://d3js.org/d3-brush) to implement health time bar brush.
3. How to integrate react and d3.js: [React + D3.js](https://2019.wattenberger.com/blog/react-and-d3)

### CODE REVIEW

File: packages/cube-frontend-ui-library/src/components/CosSegmentedBar/CosSegmentedBar.tsx [hunk 1]
```diff
@@ -115,45 +128,65 @@ export const CosSegmentedBar = (props: CosSegmentedBarProps) => {
...
-          transform={computeChildrenTransform(
-            rectHeight,
-            childrenDimensions?.marginTop,
+      <g transform={`translate(${paddingX}, 0)`}>
+        <line
+          x1={0}
+          x2={contentWidth}
+          strokeWidth={2}
+          stroke={cubeTheme.colors.functional['border-divider']}
+        />
```
Comment (lizzy-liang-bigstack) [inline packages/cube-frontend-ui-library/src/components/CosSegmentedBar/CosSegmentedBar.tsx]: I noticed there’s a grey line above the bar chart, but I’m not quite sure what it’s for. I tried removing it from the bar and everything still seems to work fine. Do you think we should remove it to better align with the design?

- Current Implementation
Screenshot 2025-07-23 at 11 07 09 AM

File: packages/cube-frontend-web-app/src/components/HealthSegmentedBar/HealthSegmentedBar.tsx [hunk 2]
```diff
@@ -1,37 +1,67 @@
...
+    [history, dateTimeRange],
   )
 
-  const commonSegmentedBarProps = {
+  const commonSegmentedBarProps: CosSegmentedBarProps = {
     className,
     width,
     segments,
+    barMarginTop: barMarginTop,
+    paddingX: paddingX,
```
Comment (lizzy-liang-bigstack) [inline packages/cube-frontend-web-app/src/components/HealthSegmentedBar/HealthSegmentedBar.tsx]: Nitpick:
We might consider using shorthand syntax here for avoiding repeating variable names as both keys and values.

**Review by lizzy-liang-bigstack — APPROVED** [review]
Hi @raven-pan,
  
Thank you for the update! I learned a lot from your PR, especially how you used `d3.js` to handle the TimeBar and its filter logic. I also found the use of lodash/fp's `pipe` function really insightful, such a simple and elegant way to group and sort data! 🚀
  
I’ve left a few minor comments below. Let’s also check if @steven-chiu-bigstack has any additional thoughts.

Regarding the UX improvement we discussed in the meeting the other day, adding a clearer indicator on the HealthBrushTimeBar to show users that the filter can be used to zoom in/out, feel free to let us know if there’s any update from the designers. Otherwise, I think it’s good to go!

File: packages/cube-frontend-web-app/src/components/HealthSegmentedBar/HealthSegmentedBar.tsx (hunk 2 above)
Comment (raven-pan) [reply packages/cube-frontend-web-app/src/components/HealthSegmentedBar/HealthSegmentedBar.tsx]: Oops! that's a big mistake, thank you for pointing it out.

Fixed by this [commit](https://github.com/bigstack-oss/cube-cos-ui/pull/575/commits/2920efaca1f09dc302dd8368d51cf20b893580ba).

File: packages/cube-frontend-ui-library/src/components/CosSegmentedBar/CosSegmentedBar.tsx (hunk 1 above)
Comment (raven-pan) [reply packages/cube-frontend-ui-library/src/components/CosSegmentedBar/CosSegmentedBar.tsx]: Oops! that's a big mistake, thank you for pointing it out.

Fixed by this [commit](https://github.com/bigstack-oss/cube-cos-ui/pull/575/commits/2920efaca1f09dc302dd8368d51cf20b893580ba).

**Comment by raven-pan** [comment]
⚠️ This PR is based on https://github.com/bigstack-oss/cube-cos-ui/pull/542, as we need to apply the latest cube-cos-openapi SDK to resolve Typescript type errors and to make the CI pass.

**Comment by raven-pan** [comment]
> Hi @raven-pan,
> 
> Thank you for the update! I learned a lot from your PR, especially how you used `d3.js` to handle the TimeBar and its filter logic. I also found the use of lodash/fp's `pipe` function really insightful, such a simple and elegant way to group and sort data! 🚀
> 
> I’ve left a few minor comments below. Let’s also check if @steven-chiu-bigstack has any additional thoughts.
> 
> Regarding the UX improvement we discussed in the meeting the other day, adding a clearer indicator on the HealthBrushTimeBar to show users that the filter can be used to zoom in/out, feel free to let us know if there’s any update from the designers. Otherwise, I think it’s good to go!

Hi @lizzy-liang-bigstack

Regarding  the suggestion to add a clearer indicator on the HealthBrushTimeBar to show users that the filter can be used to zoom in/out, I created a UI/UX enhancement ticket to track it: https://github.com/orgs/bigstack-oss/projects/6/views/1?pane=issue&itemId=121766632&issue=bigstack-oss%7Ccube-cos-ui%7C582.

Thanks!
