### PR TITLE
fix: events page related issues

### LINKED ISSUE #222: Page - `Events Listing Page` pagination behaviour
The behaviour of `Events Listing Page` pagination is not working properly.
No screenshots available at the time.

### LINKED ISSUE #251: [Bug]: Switching pages causes the view to jump back to page 1
## Describe the bug

Switching pages causes the view to jump back to page 1.
It seems that the API for page=1 is being requested again, which is causing the tab switching to fail.

https://github.com/user-attachments/assets/7d6c5b24-1993-49d9-a9bd-5c1c42049f7e

## Version

CUBE_3.0.0_20250414-1327_fa8abf5

## To Reproduce

1. Go to Events Page
2. Switch the pages at the bottom section
3. Tab switching is not working

## Expected behavior

Switch to the correct page

## Screenshots

Image

Image

### LINKED ISSUE #253: [Bug]: The time picker selection is not consistent with the date passed in the API
## Describe the bug

The time picker selection is not consistent with the date passed in the API.
It seems that incorrect values were passed to the API, which resulted in the wrong date being returned

https://github.com/user-attachments/assets/b53e420d-3e93-42a0-8aac-4ecaf83bf5ac

## Version

What version of the product is affected [e.g. 3.x.x].

## To Reproduce

1. Go to Events page
2. Click on Time picker ,selection 04/15~04/17
3. Returned incorrect date values

## Expected behavior

The values returned by the API should match the selected range of 04/15 to 04/17.

## Screenshots

Image

### LINKED ISSUE #256: UI library - Date Picker UI update
- replace `Cancel` button with `Reset` button
- [mockup](https://www.figma.com/design/T95ymFSTSDKdmr9WEjylQE/COS-Design-System-2024?node-id=5841-9065&m=dev)

### PR DESCRIPTION
**Pull request by lizzy-liang-bigstack**
#### What type of PR is this?

- Feature
- Fix

##### 1) `CosDatePicker` ➡️ commit [acbf525](https://github.com/bigstack-oss/cube-cos-ui/pull/257/commits/acbf5253ad6c843f5b1e130a76faf9fb7be52b8f)
- Implement `Reset` functionality in `CosDatePicker` 
- Refactor the component to expose displayed dates

https://github.com/user-attachments/assets/a13750f8-94e5-40eb-910c-564a8eaad97e

##### 2) Update  `CosDatePicker` usage accordingly ➡️ commit [5d15bf9](https://github.com/bigstack-oss/cube-cos-ui/pull/257/commits/5d15bf92518351fecab9c371ba748effc9fac9a6)
- `Events` listing page
- `Support Files` page

https://github.com/user-attachments/assets/4727365c-cb9e-4a61-9703-6147bcca9d68

##### 3) Fix pagination behaviour on the Events listing page ➡️ commit [0a2424c](https://github.com/bigstack-oss/cube-cos-ui/pull/257/commits/0a2424c19d8de8f6518816b374024e6eb14093f1)

https://github.com/user-attachments/assets/4f888d59-c2be-4e10-bc2c-30caceb39212

##### 4) Resolve time mismatch between date picker and API requests on the Events listing page ➡️ commit [ad71221](https://github.com/bigstack-oss/cube-cos-ui/pull/257/commits/ad71221007b4264dbf7a688caa308fa5f3e15f25)

Screenshot 2025-04-21 at 11 15 24 AM

#### Which issue(s) this PR fixes

Fixes #222 ➡️ commit [0a2424c](https://github.com/bigstack-oss/cube-cos-ui/pull/257/commits/0a2424c19d8de8f6518816b374024e6eb14093f1)

Fixes #251 (same issue as #222) 

Fixes #253 ➡️ commit [ad71221](https://github.com/bigstack-oss/cube-cos-ui/pull/257/commits/ad71221007b4264dbf7a688caa308fa5f3e15f25)

Fixes #256 ➡️ commit [acbf525](https://github.com/bigstack-oss/cube-cos-ui/pull/257/commits/acbf5253ad6c843f5b1e130a76faf9fb7be52b8f) & [5d15bf9](https://github.com/bigstack-oss/cube-cos-ui/pull/257/commits/5d15bf92518351fecab9c371ba748effc9fac9a6)

#### Special notes for your reviewer

> Note

#### Additional documentation

```docs

```

### CODE REVIEW

File: packages/cube-frontend-web-app/src/pages/events/index/_components/EventsTable/utils.ts [hunk 1]
```diff
@@ -1,59 +1,95 @@
...
+    stop = selectedEndDate.format()
   }
 
-  return filterKey
+  /**
+   * Check if start and stop are the same and modify the times
+   * - start => "YYYY-MM-DD 00:00:00"
+   * - stop  => "YYYY-MM-DD 23:59:59"
+   */
+  if (start && start === stop) {
```
Comment (raven-pan) [inline packages/cube-frontend-web-app/src/pages/events/index/_components/EventsTable/utils.ts]: Maybe we should always use `startOf('day')` for `start` and `endOf('day')` for 'end?
We could remove the `if` condition like this:

```tsx
start = selectedStartDate!.startOf('day').format()
stop = selectedStartDate!.endOf('day').format()
```

What do you think?

File: packages/cube-frontend-web-app/src/pages/events/index/_components/EventsTable/useEventsQuery.ts [hunk 2]
```diff
@@ -1,95 +1,125 @@
...
-        newParams.set(key, value)
-      } else {
-        newParams.delete(key)
-      }
-    })
-    setSearchParams(newParams, { replace: true })
+  const onKeywordChange = (keyword: string): void => {
+    setEventsQuery((prev) => ({
+      ...prev,
+      keyword,
```
Comment (raven-pan) [inline packages/cube-frontend-web-app/src/pages/events/index/_components/EventsTable/useEventsQuery.ts:81]: When `keyword`, `pageSize` and `filters` change, set pageNum to `1` seems more intuitive for the user.

What do you think?

File: packages/cube-frontend-web-app/src/pages/events/index/_components/EventsTable/EventsTableFilter.tsx [hunk 3]
```diff
@@ -1,70 +1,163 @@
...
+      })
+    }
+  }
+
+  const onTypeChange = (type: GetEventsTypeEnum) => {
+    onTypeChangeProp(type)
+    onAllFilterReset()
+  }
+
+  const showAllFilterReset =
```
Comment (raven-pan) [inline packages/cube-frontend-web-app/src/pages/events/index/_components/EventsTable/EventsTableFilter.tsx]: nitpick: we can refactor it to:

```ts
const showAllFilterReset = Object.values(eventsQuery).some((v) => !!v)
```

File: packages/cube-frontend-web-app/src/pages/events/index/_components/EventsTable/utils.ts [hunk 4]
```diff
@@ -1,59 +1,95 @@
...
+  }
+
+  if (selectedEndDate) {
+    stop = selectedEndDate.format()
   }
 
-  return filterKey
+  /**
+   * Check if start and stop are the same and modify the times
+   * - start => "YYYY-MM-DD 00:00:00"
```
Comment (raven-pan) [inline packages/cube-frontend-web-app/src/pages/events/index/_components/EventsTable/utils.ts]: This date format seems different from the OpenAPI spec.
Maybe we need to confirm which format is expected?

image

**Review by raven-pan — COMMENTED** [review]
The date picker displays incorrectly after reloading the page.

https://github.com/user-attachments/assets/85c916d1-7b70-4fb2-a4bd-d445b983e0aa

File: packages/cube-frontend-web-app/src/pages/events/index/_components/EventsTable/useEventsQuery.ts (hunk 2 above)
Comment (lizzy-liang-bigstack) [reply packages/cube-frontend-web-app/src/pages/events/index/_components/EventsTable/useEventsQuery.ts:81]: Good idea - It definitely sounds like a UX improvement!

File: packages/cube-frontend-web-app/src/pages/events/index/_components/EventsTable/EventsTableFilter.tsx (hunk 3 above)
Comment (lizzy-liang-bigstack) [reply packages/cube-frontend-web-app/src/pages/events/index/_components/EventsTable/EventsTableFilter.tsx]: Actually, we are checking whether to show the filter reset button based on parts of the `eventsQuery` values. For example, `type`, `pageSize`, and `pageNum` will always exist, so we need to exclude these values from the check. However, I agree that the suggested function is simpler and easier to read! I'll update the syntax accordingly.

File: packages/cube-frontend-web-app/src/pages/events/index/_components/EventsTable/utils.ts (hunk 4 above)
Comment (lizzy-liang-bigstack) [reply packages/cube-frontend-web-app/src/pages/events/index/_components/EventsTable/utils.ts]: The format follows the Swagger documentation, as shown in the picture.
I'll update the comments — sorry for the confusion!

File: packages/cube-frontend-web-app/src/pages/events/index/_components/EventsTable/utils.ts (hunk 1 above)
Comment (lizzy-liang-bigstack) [reply packages/cube-frontend-web-app/src/pages/events/index/_components/EventsTable/utils.ts]: That's a great point! However, implementing the function you mentioned here could introduce an issue—specifically, when a user navigates from the `Chart Page` to the listing page, the dates need to respect the selected `timeRange`. Instead, I’ll address this at the moment when the dates from the `Date Picker` is applied. Thanks for pointing put! :)

**Comment by lizzy-liang-bigstack** [comment]
The issue of aligning `CosDatePicker` with the provided timezone (of where data center locates) will be addressed in a separate ticket ([#286](https://github.com/orgs/bigstack-oss/projects/6/views/1?pane=issue&itemId=108346271&issue=bigstack-oss%7Ccube-cos-ui%7C286)).

File: packages/cube-frontend-web-app/src/pages/events/index/_components/EventsTable/EventsTableFilter.tsx (hunk 3 above)
Comment (raven-pan) [reply packages/cube-frontend-web-app/src/pages/events/index/_components/EventsTable/EventsTableFilter.tsx]: Sure, you're right!

**Review by raven-pan — APPROVED** [review]
