### PR TITLE
465 update search bar placeholder text on Event Listing page

### LINKED ISSUE #465: [Bug]: Search bar indicator text
## Describe the bug

Image
THe indicator should be general terms.

## To Reproduce

1. Go to 'Events'
2. View search bar

## Expected behavior

only 'Search'

### PR DESCRIPTION
**Pull request by lizzy-liang-bigstack**
#### What type of PR is this?

- Fix

#### What this PR does / why we need it

- Update Searchbar placeholder text on Event Listing page

Screenshot 2025-05-22 at 11 43 01 AM

#### Which issue(s) this PR fixes

Fixes #465 

#### Special notes for your reviewer

> Note

#### Additional documentation

```docs

```

### CODE REVIEW

File: packages/cube-frontend-web-app/src/pages/events/index/_components/EventsTable/EventsTableFilter.tsx [hunk 1]
```diff
@@ -120,6 +120,7 @@ export const EventsTableFilter = (props: EventsTableFilterProps) => {
       <div className="flex items-center gap-3">
         <div className="flex items-center gap-2">
           <CosSearchBarFilter
+            placeholder="Search"
```
Comment (raven-pan) [inline packages/cube-frontend-web-app/src/pages/events/index/_components/EventsTable/EventsTableFilter.tsx]: Discussion:

How about setting the default placeholder to `Search`, since `Search` is a more general term.

image

Maybe we can discuss this with the designers?

Figma Reference:
https://www.figma.com/design/T95ymFSTSDKdmr9WEjylQE/COS-Design-System-2024?node-id=752-10684&m=dev

**Review by raven-pan — APPROVED** [review]
