### PR TITLE
258 node details page adjustments

### LINKED ISSUE #258: [Bug]:Three issues on the Nodes Detail page
## Describe the bug

After confirming with the designer:

1.There is an action button, but it only has the "Create Support Files" function.

2.The Status column will remain, but it won't have any functionality.

3.Data parsing error in the Metadata field

Image

Image

## Version

What version of the product is affected [e.g. 3.x.x].

## To Reproduce

1. Go to Nodes page
2. Click "cc1" entry Detail page

## Expected behavior

1.Action button exists, has create Support File function
2.Displayed Status
3.Correct value

Image

### PR DESCRIPTION
**Pull request by steven-chiu-bigstack**
#### What type of PR is this?

Feat

#### What this PR does / why we need it

In Node Details page:

1. Implement the Action overflow menu (action button).
2. Adjust the content of the "Status" column.
3. Add "Availability" column to the device table.

#### Which issue(s) this PR fixes

Close #258 

https://github.com/user-attachments/assets/48a62fb6-db7b-4495-afa6-aa38519dbf2f

### CODE REVIEW

**Comment by steven-chiu-bigstack** [comment]
Hi @raven-pan @lizzy-liang-bigstack 
Just letting you know this PR is now ready for review, thank you so much! 🙏

File: packages/cube-frontend-web-app/src/pages/node/_components/CreateSupportFilesModal.tsx [hunk 1]
```diff
@@ -1,39 +1,72 @@
...
-    isCreating,
     selectedNodes,
     comments,
     onCommentsChange,
-    onCreateClick,
     onCloseClick,
+    onSuccess,
   } = props
 
+  const dataCenter = useContext(DataCenterContext)
```
Comment (lizzy-liang-bigstack) [inline packages/cube-frontend-web-app/src/pages/node/_components/CreateSupportFilesModal.tsx]: Note: The `dataCenter` should follow the current context structure.

File: packages/cube-frontend-web-app/src/pages/node/_components/CreateSupportFilesModal.tsx [hunk 2]
```diff
@@ -1,39 +1,72 @@
...
+    useCosMutationRequest(
+      supportFilesApi.createSupportFiles as (
+        params: SupportFilesApiCreateSupportFilesRequest,
+      ) => Promise<CosApiResponse<undefined>>,
+    )
+
+  const onCreateClick = async (): Promise<void> => {
+    try {
+      await createSupportFilesApi({
+        dataCenter: dataCenter.name,
```
Comment (lizzy-liang-bigstack) [inline packages/cube-frontend-web-app/src/pages/node/_components/CreateSupportFilesModal.tsx]: Note: To ensure `dataCenter` is always accessible, we need to put the non-null assertion (!) operator here.

**Review by lizzy-liang-bigstack — COMMENTED** [review]
#####  1. 
There’s another issue mentioned in ticket #258 regarding a data parsing error in the Metadata field. It doesn’t seem to be addressed in this PR—just wanted to confirm whether this will be handled in a separate PR?

Screenshot 2025-04-24 at 3 44 46 PM

##### 2. 
It looks like the table might have a 5px-ish border radius, but I couldn’t find any specific details in the Figma. Just a small note—feel free to ignore this comment!

Screenshot 2025-04-24 at 3 12 26 PM

Screenshot 2025-04-24 at 4 41 59 PM

**Comment by steven-chiu-bigstack** [comment]
Hi @lizzy-liang-bigstack 

>There’s another issue mentioned in ticket https://github.com/bigstack-oss/cube-cos-ui/issues/258 regarding a data parsing error in the Metadata field.

Thanks for the heads up! I missed this one; will fix it within this PR. 🙏 

>It looks like the table might have a 5px-ish border radius, but I couldn’t find any specific details in the Figma.

Good catch! Let me fix it real quick.

**Comment by steven-chiu-bigstack** [comment]
Bug fixes:

1. Summary table border radius (and table width)

   {BC41CE54-E5E4-4BD1-AB40-CF1212491905}

2. Events table `metadata` column

   image

**Review by lizzy-liang-bigstack — APPROVED** [review]
