### PR TITLE
323 update Event Chart page

### LINKED ISSUE #309: [Bug]: Bar Chart Top Values Clipped When at Maximum Height
## Describe the bug

The value is cut off by the top edge of the bar

Image

## Version

CUBE_3.0.0_20250417-2230_02ed2ff

## To Reproduce

1. Go to Events / Chart page

## Expected behavior

The top space should allow room for the value

### LINKED ISSUE #310: [Bug]: Event chart text color
## Describe the bug

Image

Image

## Version

CUBE_3.0.0_20250417-2230_02ed2ff

## To Reproduce

1. Go to 'Event chart'
2. View the label color

## Expected behavior

As UI library

### LINKED ISSUE #311: [Bug]: Event chart filter issues
## Describe the bug

Image
Can discuss in today's scrum

## Version

CUBE_3.0.0_20250417-2230_02ed2ff

### LINKED ISSUE #323: [Task]: Event Chart – Update Chart Label, Tooltip, and Filter Dropdown
1. Update the filter dropdown to use checkboxes to support multiple selections.

Image

2. On the Host tab, display the host name in the chart label and tooltip.

Image

3. On the Instance tab, display the instance ID in the chart label and tooltip.

Image

4. The chart layout mockup has been updated: [Mockup](https://www.figma.com/design/kRJ5MUAkMF0AYgXCeChtZn/COS-management-UI-Redesign-v.3?node-id=9229-9908&m=dev)

### PR DESCRIPTION
**Pull request by lizzy-liang-bigstack**
#### What type of PR is this?

- Feat

#### What this PR does / why we need it

1. Dropdown Filter 
- Updated the filter in the Event Chart page from single to multi-selection.

Screenshot 2025-05-06 at 1 32 40 PM 2

- Corresponding API requests have been updated accordingly.

Screenshot 2025-05-06 at 11 13 34 AM 2
　
2. Pie Chart
- When there are 12 or fewer items, labels are arranged in a horizontal (row-based) layout.

Screenshot 2025-05-06 at 3 26 32 PM

- For more than 12 items, labels switch to a vertical (column-based) layout.

Screenshot 2025-05-06 at 3 26 53 PM

- Label order follows a top-to-bottom, left-to-right flow.

Screenshot 2025-05-06 at 3 26 53 PM 2

　
3. Tooltip
- Background color updated according to the design.
- Tooltip content:
    - Pie Chart:
         - `System`: Proportion
         - `Host`: Proportion, Host
         - `Instance`: Proportion, Instance Name, Instance ID
    - Bar Chart:
         - `System`: Counting
         - `Host`: Counting, Host
         - `Instance`: Counting, Instance Name, Instance ID
        
　
4. Hover Effect
- Bar chart hover styles have been aligned with the design specs.
 
Screenshot 2025-05-06 at 3 17 12 PM 3

 　
5. Bug Fix
- Fixed an issue where bar chart top values were clipped when reaching the maximum height.

Screenshot 2025-05-06 at 3 17 12 PM 2

#### Which issue(s) this PR fixes

- Fixes #309 
- Fixes #310
- Fixes #311 (same as the issue 323)
- Fixes #323 

#### Special notes for your reviewer

In this change, I update the Pie Chart's canvas width to 380px because the instance tooltip now includes the instance ID. If the canvas remains at the original 220px, the ID would overflow beyond the canvas and get cut off...

I've noticed that others have encountered similar issues ([reference](https://github.com/chartjs/Chart.js/issues/622)), and there doesn't seem to be a good solution for now—unless we customize the tooltip, which would require more effort. Therefore, as a workaround, I've adjusted the canvas width to prevent the tooltip information from being truncated.

#### Additional documentation

```docs

```

### CODE REVIEW

File: packages/cube-frontend-web-app/src/pages/events/chart/_components/EventsChartProportion/PieChart/PieChartLabel.tsx [hunk 1]
```diff
@@ -1,46 +1,43 @@
...
-    onMouseLeave,
-    redirectUrl,
-  } = props
+  const { event, eventsType, isBlur, onMouseEnter, onMouseLeave, redirectUrl } =
+    props
+
+  const chartLabel = getChartLabelByEventsType(eventsType, event)
 
   return (
     <a
```
Comment (steven-chiu-bigstack) [inline packages/cube-frontend-web-app/src/pages/events/chart/_components/EventsChartProportion/PieChart/PieChartLabel.tsx]: We should use the `Link` component from `react-router` to replace `a` to prevent full reloads from happening on click.

File: packages/cube-frontend-web-app/src/pages/events/chart/_components/utils.ts [hunk 2]
```diff
@@ -127,43 +138,90 @@ export const getRequestQueryByChartType = (
...
+    const first8DigitOfInstanceId = event.instanceId?.split('-')[0]
+      ? ` (${event.instanceId?.split('-')[0]})`
+      : ''
+    return event.id + first8DigitOfInstanceId
+  }
+
+  return event.id
+}
+
+export const convertHexToRGBA = (hexCode: string) => {
```
Comment (steven-chiu-bigstack) [inline packages/cube-frontend-web-app/src/pages/events/chart/_components/utils.ts]: Nitpick: Typically, an RGBA conversion uses an alpha value of 1.0, so 0.3 is unconventional. We could rename the function or add an optional `alpha = 0.3` parameter to the list for clarity. For example: `const hexToRGBA = (hexCode: string, alpha = 0.3) => {...}`

File: packages/cube-frontend-web-app/src/pages/events/chart/_components/useRankedEvents.ts [hunk 3]
```diff
@@ -33,5 +38,23 @@ export const useRankedEvents = (
...
+   * Sort the events in descending order based on the 'percent' field
+   * then slice to keep only the top 24 events.
+   * Add a `uniqueId` to each ranked event, as the original event ID
+   * may not be unique. The `uniqueId` helps distinguish each entry.
+   */
+  const rankedEvents = useMemo(() => {
+    const events = data ? data.events : []
+    const sortedEvents = events
+      .sort((a, b) => b.percent - a.percent)
+      .slice(0, 24)
```
Comment (steven-chiu-bigstack) [inline packages/cube-frontend-web-app/src/pages/events/chart/_components/useRankedEvents.ts]: From the code above it looks like we already have `limit: 24` that limits the data count of the events. Just wondering if `.slice(0, 24)` is still necessary?

{2B2DC459-2669-44BE-BB06-9032FF08644A}

File: packages/cube-frontend-web-app/src/pages/events/chart/_components/useRankedEvents.ts [hunk 4]
```diff
@@ -33,5 +38,23 @@ export const useRankedEvents = (
...
+
+    return sortedEvents.map((event) => ({
+      ...event,
+      uniqueId: uniqueId(`${event.id}-${event.category}-${event.number}`),
```
Comment (steven-chiu-bigstack) [inline packages/cube-frontend-web-app/src/pages/events/chart/_components/useRankedEvents.ts]: Lodash's [uniqueId](https://www.lodashjs.com/docs/lodash.uniqueId) function ensures the returned value is unique, so we can safely use `uniqueId()` alone or add a prefix such as `uniqueId('ranked-event')` to make it easier to identify during debugging.

File: packages/cube-frontend-web-app/src/pages/events/chart/_components/useEventsChartQuery.ts [hunk 5]
```diff
@@ -42,8 +43,13 @@ type UseEventsChartQuery = {
   onTimeRangeChange: (timeRange: ChartTimeRanges) => void
   onFieldChange: <Key extends keyof FilterOptions>(
     key: Key,
-    value: FilterOptions[Key] | undefined,
+    value: string,
   ) => void
+  onFieldAllSelect: <Key extends keyof FilterOptions>(
+    key: Key,
+    options: FilterOptions[Key],
+  ) => void
```
Comment (steven-chiu-bigstack) [inline packages/cube-frontend-web-app/src/pages/events/chart/_components/useEventsChartQuery.ts:51]: Both `onFieldChange` and `onFieldAllSelect` handle only array properties (multi-selection with checkboxes) in the query. To ensure safety, it is suggested to exclude non-array properties such as `type` and `past` from `key`.

I'm not sure if there's an easier way to do it, but something like the following could probably work:

```ts
type ArrayQueryKey = {
  [K in keyof ChartQuery]: ChartQuery[K] extends unknown[] | undefined
    ? K
    : never
}[keyof ChartQuery]
```

{26BB9C54-9A80-416A-8668-2BDCB0FD89CB}

File: packages/cube-frontend-web-app/src/pages/events/chart/_components/FilterDropdown.tsx [hunk 6]
```diff
@@ -62,13 +58,17 @@ export const FilterDropdown = <Key extends keyof FilterOptions>(
...
+      selectedItems={selectedItems}
+      onAllCheckChange={handleAllClick}
       disabled={false}
       isLoading={isLoading}
     >
       <CosDropdown.Trigger placeholder={upperFirst(filterLabel)}>
-        {selectedItem?.[0] ?? undefined}
+        {selectedValue?.length
+          ? `${upperFirst(filterLabel)}: (${selectedValue?.length ?? 0})`
+          : undefined}
```
Comment (steven-chiu-bigstack) [inline packages/cube-frontend-web-app/src/pages/events/chart/_components/FilterDropdown.tsx:70]: Discussion: In Raven's dropdown text/placeholder adjustments [PR](https://github.com/bigstack-oss/cube-cos-ui/pull/329), he used words without numbers (e.g. "Statuses" instead of "Statuses (3)") when items are selected in the dropdown. Do we wish to do the same here for consistency? "Items (count)" seems fine to me, though.

File: packages/cube-frontend-web-app/src/pages/events/chart/_components/EventsChartComparison/BarChart/barChartUtils.ts [hunk 7]
```diff
@@ -64,37 +82,79 @@ export const drawValuePlugin: Plugin<'bar'> = {
...
     scales: {
       x: {
         grid: {
           display: false,
         },
+        ticks: {
+          color: chartData.items.map((item) => item.labelColor),
+        },
+      },
+      y: {
```
Comment (steven-chiu-bigstack) [inline packages/cube-frontend-web-app/src/pages/events/chart/_components/EventsChartComparison/BarChart/barChartUtils.ts:105]: It looks like the title to the left are missing from the implementation:

image

We can use `StoragePanels/StorageChart/utils.ts:97` as a reference and add `y.title` for the title:

{1DFADD90-D923-475F-AAF7-88241841E2FF}

File: packages/cube-frontend-web-app/src/pages/events/chart/_components/EventsChartComparison/BarChart/barChartUtils.ts [hunk 8]
```diff
@@ -47,7 +65,7 @@ export const getChartData = (
  */
 export const drawValuePlugin: Plugin<'bar'> = {
   id: 'drawValuePlugin',
-  afterDraw: (chart) => {
+  afterDatasetsDraw: (chart) => {
     const ctx = chart.ctx
     ctx.font = '11px Inter'
```
Comment (steven-chiu-bigstack) [inline packages/cube-frontend-web-app/src/pages/events/chart/_components/EventsChartComparison/BarChart/barChartUtils.ts]: Nitpick: We can retrieve values from `cubeTheme` for slightly better maintainability. We can make an util function to make similar usages easier in the future:

```ts
const fontFamily = cubeTheme.fontFamily.inter[0]
const fontSize = cubeTheme.fontSize['primary-body5'][0]
ctx.font = `${fontSize} ${fontFamily}`
```

File: packages/cube-frontend-web-app/src/pages/events/chart/_components/EventsChartComparison/BarChart/barChartUtils.ts [hunk 9]
```diff
@@ -47,7 +65,7 @@ export const getChartData = (
  */
 export const drawValuePlugin: Plugin<'bar'> = {
```
Comment (steven-chiu-bigstack) [inline packages/cube-frontend-web-app/src/pages/events/chart/_components/EventsChartComparison/BarChart/barChartUtils.ts]: I notice the value label at the top of the bars are always opaque:

image

It's surprising that ChartJS doesn't natively support this common feature, requiring us to write a custom plugin. We can adjust `drawValuePlugin` a little bit (either put it in `EventsChartComparison/BarChart/BarChart.tsx` or make it into a function) to achieve the desired effect:

https://github.com/user-attachments/assets/780dc5da-837c-423b-bc58-086653f9e3e2

The idea is to have a **Ref** that stores the hovered event index, and change the color of the label right before we draw it in canvas:

{5AEB65FE-8C83-4397-9248-07A4C35E06B1}

**Review by steven-chiu-bigstack — APPROVED** [review]
Hi @lizzy-liang-bigstack, looks good overall! 🚀 
I focused primarily on bugs and maintainability rather than covering every detail. Let me know if there's anything you'd like to discuss. 🙏

File: packages/cube-frontend-web-app/src/pages/events/chart/_components/EventsChartComparison/BarChart/barChartUtils.ts (hunk 9 above)
Comment (steven-chiu-bigstack) [reply packages/cube-frontend-web-app/src/pages/events/chart/_components/EventsChartComparison/BarChart/barChartUtils.ts]: Update:

I said using Ref in my previous comment because it didn't work when I use state at the first time. But now I realized components from `react-chartjs` do not always respond to hot reload. Maybe that's why it didn't work when I tried state. You could give state a try and see if it works.

File: packages/cube-frontend-web-app/src/pages/events/chart/_components/useRankedEvents.ts (hunk 3 above)
Comment (lizzy-liang-bigstack) [reply packages/cube-frontend-web-app/src/pages/events/chart/_components/useRankedEvents.ts]: You're right! I'll remove the `.slice` operation from the array since it's redundant.

File: packages/cube-frontend-web-app/src/pages/events/chart/_components/useEventsChartQuery.ts (hunk 5 above)
Comment (lizzy-liang-bigstack) [reply packages/cube-frontend-web-app/src/pages/events/chart/_components/useEventsChartQuery.ts:51]: There’s already a type FilterKeys that excludes non-array properties from the ChartQuery keys.
I’ll reuse this type for the onFieldChange and onFieldAllSelect functions.
Thank you! :)

```
type FilterKeys = Extract<
  keyof ChartQuery,
  | 'proportionCategory'
  | 'comparisonCategory'
  | 'proportionSeverity'
  | 'comparisonSeverity'
  | 'proportionHost'
  | 'comparisonHost'
  | 'proportionInstance'
  | 'comparisonInstance'
>
```

File: packages/cube-frontend-web-app/src/pages/events/chart/_components/FilterDropdown.tsx (hunk 6 above)
Comment (lizzy-liang-bigstack) [reply packages/cube-frontend-web-app/src/pages/events/chart/_components/FilterDropdown.tsx:70]: That's a good point — aligning the dropdown label with the others makes sense.
