### PR TITLE
ui library - update date picker behaviour and ui

### LINKED ISSUE #230: [Bug]: A gap between Wednesday and Thursday
## Describe the bug

[10.32.35.1](https://10.32.35.1:4443)
A gap between Wednesday and Thursday

Image

## Version

CUBE_3.0.0_20250329-2037_b80b9d0
cube-cos-ui - 1932877

## To Reproduce

1. login, and switch to Events page
2. press the Time button
3. select any day that includes Wed. & Thu.

## Expected behavior

No gap in any consecutive days unit

### LINKED ISSUE #234: UI Library - Date Picker behaviour update
User Flow (updated with designer):

1. The selected dates will be applied when the "Apply" button is clicked.

2. If the user clicks "Cancel" or anywhere outside the date picker, the dates will revert to their previous state before editing.

### PR DESCRIPTION
**Pull request by lizzy-liang-bigstack**
#### What type of PR is this?

- Fix

##### 1) Remove the gap between `<DayButton />`

|       | Before  | After  |
|------------|--------|--------|
| Gap    | Screenshot 2025-04-14 at 5 23 42 PM | Screenshot 2025-04-14 at 5 23 42 PM |

##### 2) Update 

- Changes will only be applied to the selected date when users click "Apply" button. 

- If the user clicks "Cancel" or anywhere outside the date picker, the dates will revert to their previous state before editing.

https://github.com/user-attachments/assets/c6395db7-6052-4f35-aacf-9b4a4ee2562b

#### Which issue(s) this PR fixes

- Close #230 

- Close #234

#### Special notes for your reviewer

> Note

#### Additional documentation

```docs

```

### CODE REVIEW

File: packages/cube-frontend-ui-library/src/components/CosDatePicker/CosDatePickerMenu.tsx [hunk 1]
```diff
@@ -33,12 +34,12 @@ export const CosDatePickerMenu = () => {
       <div className="flex gap-4">
         <CosDatePickerInput
```
Comment (steven-chiu-bigstack) [inline packages/cube-frontend-ui-library/src/components/CosDatePicker/CosDatePickerMenu.tsx:35]: It looks like `CosDatePickerInput` utilizes `CosTableInput`, but `CosTableInput` has a fixed space preserved for the error icon, leading to a style issue:

- Current implementation:
   - {A15BA77B-3317-4F10-B439-32CAEA7EED1B}
- Mockup:
   - {46B8C356-8804-40CE-89B7-0048B56D4509}

Do you think it make sense to add a prop to `CosTableInput` that hides the error icon? There's no error icon/message outlined for the date picker inputs at the moment.

**Review by steven-chiu-bigstack — APPROVED** [review]
LGTM! 👍
