### PR TITLE
341 display roles from data center

### LINKED ISSUE #341: [Bug]: Roles should only display cloud or/ edge nodes at a time
## Describe the bug

 Roles should only display cloud or/ edge nodes

1. Home 上方圖表
2. Home chart
3. Nodes nodes roles Dropdown 

## To Reproduce

1. Go to 'Home 上方圖表'/ 'Home chart'/ 'Nodes nodes roles Dropdown ''

## Expected behavior

Roles should only display cloud or/ edge nodes

## Screenshots

##Additional context

### PR DESCRIPTION
**Pull request by lizzy-liang-bigstack**
#### What type of PR is this?

- Feat

#### What this PR does / why we need it

- Ensure the displayed `Roles` are coming from data center - they should be either cloud or edge nodes at a time

#### 1) Home/Overview

Screenshot 2025-05-08 at 5 02 30 PM

#### 2) Home/Chart

Screenshot 2025-05-08 at 5 02 58 PM

#### 3) Nodes

https://github.com/user-attachments/assets/2d52e76b-be09-45a7-958c-2d0fad1f101e

#### 4) Support Files

Screenshot 2025-05-08 at 5 33 56 PM

#### 5) License - `Get Hardware Serial Number` modal

Screenshot 2025-05-08 at 5 34 10 PM

#### Which issue(s) this PR fixes

Fixes #341 

#### Special notes for your reviewer

> Note

#### Additional documentation

```docs

```

### CODE REVIEW

File: packages/cube-frontend-web-app/src/pages/home/utils.ts [hunk 1]
```diff
@@ -31,41 +38,44 @@ export const toMetricsChart = (metrics: GetMetricsResponseData) => {
     },
   ]
 
-  // TODO: define roles enum in the openAPI.
   const roleCountInfos: CosCountSegmentedChartCountInfo[] = [
```
Comment (steven-chiu-bigstack) [inline packages/cube-frontend-web-app/src/pages/home/utils.ts]: Nitpick: We can change the declaration of `roleCountInfos` from `const roleCountInfos: CosCountSegmentedChartCountInfo[] = [...]` to `const roleCountInfos = [...] satisfies CosCountSegmentedChartCountInfo[]` to avoid using `as` for type casting on the `name` field below.

File: packages/cube-frontend-web-app/src/pages/home/utils.ts [hunk 2]
```diff
@@ -31,41 +38,44 @@ export const toMetricsChart = (metrics: GetMetricsResponseData) => {
...
+      name: GetDataCentersResponseDataInnerRolesEnum.Moderator,
       color: 'fill-chart-5',
       count: metrics.host.role.moderator.count,
     },
   ]
 
-  const totalRoles: number = Object.values(metrics.host.role).reduce(
+  const totalRoles = roleCountInfos.filter((info) =>
+    roles.includes(info.name as GetDataCentersResponseDataInnerRolesEnum),
+  )
```
Comment (steven-chiu-bigstack) [inline packages/cube-frontend-web-app/src/pages/home/utils.ts]: Nitpick: We can map `totalRoles` to capitalize the `name` field for display purpose:

- Before
   image
- Current implementation
   image

**Review by steven-chiu-bigstack — APPROVED** [review]
Hi @lizzy-liang-bigstack 

Nice work, thanks for helping out with this one! 👍👍👍 
Besides the files you modified, there are still some places using the hard-coded roles and type from `cube-frontend-web-app/src/utils/node.ts`:

{3BAA34BF-BC4A-496E-9982-1A7D5075B570}

Just to let you know that I'll remove this file and replace those code with `dataCenter.roles` and `GetDataCentersResponseDataInnerRolesEnum` respectively later on. 🙏

File: packages/cube-frontend-web-app/src/utils/number.ts [hunk 3]
```diff
@@ -1,4 +1,5 @@
 export const toPercentage = (used: number, total: number) => {
+  if (total === 0) return 0
```
Comment (steven-chiu-bigstack) [inline packages/cube-frontend-web-app/src/utils/number.ts:2]: Fix NaN issue when `total` is 0:

image
