### PR TITLE
479 fix(web-app): edit tunings hosts are not selected by default bug

### LINKED ISSUE #479: [Bug]: Edit Tunings Hosts Are Not Selected By Default
## Describe the bug

When editing a tuning, host checkboxes are not checked by default.

## To Reproduce

1. Go to Events Page -> Tunings tab
2. Click on the edit button of any modified tuning
3. Click "Next" to proceed to the "Select Hosts" step
4. See no checkbox is checked

## Expected behavior

Checkboxes should be checked by default based on the hosts the edited tuning applies to.

## Screenshots

https://github.com/user-attachments/assets/dd665d02-3e1f-4c3a-8349-4e33eb522250

### PR DESCRIPTION
**Pull request by steven-chiu-bigstack**
#### What type of PR is this?

Fix

#### What this PR does / why we need it

Fix Edit Tunings page hosts are not selected by default bug.

#### Which issue(s) this PR fixes

Close #479 

https://github.com/user-attachments/assets/e4743827-febe-425d-ad5c-373674d38b26

### CODE REVIEW

File: packages/cube-frontend-web-app/src/components/UpsertTunings/_components/useEditTuningsPayload.ts [hunk 1]
```diff
@@ -45,32 +51,16 @@ export const useEditTuningsPayload = (
...
-      if (!prev) {
-        return prev
-      }
-      return {
-        ...prev,
-        selectedHosts: validHosts,
-      }
-    })
-  }, [nodes, initialData])
+  }, [specs, nodes, initialData])
```
Comment (steven-chiu-bigstack) [inline packages/cube-frontend-web-app/src/components/UpsertTunings/_components/useEditTuningsPayload.ts:63]: Payload initialization can actually be done in 1 effect, so this one is removed for cleaner code.

File: packages/cube-frontend-web-app/src/components/UpsertTunings/_components/useEditTuningsPayload.ts [hunk 2]
```diff
@@ -19,15 +19,21 @@ type UseEditTuningsPayload = {
...
   initialData: EditTuningsInitialData,
   selectedSpec: ListTuningSpecResponseDataInner | undefined,
+  nodes: Node[],
 ): UpsertTuningsPayload => {
-  const { specName, value } = initialData
+  const { specName, value, hosts } = initialData
+
+  const selectedHosts: HostWithRole[] = hosts
+    ? filterValidHosts(nodes, hosts)
+    : []
```
Comment (steven-chiu-bigstack) [inline packages/cube-frontend-web-app/src/components/UpsertTunings/_components/useEditTuningsPayload.ts:28]: By the way, `initialData.hosts` will be `undefined` when the user is editing a default tuning (that is, a non-modified one). That's why we have this null check.

**Review by lizzy-liang-bigstack — APPROVED** [review]
LGTM!

**Review by raven-pan — APPROVED** [review]
LGTM!

**Comment by steven-chiu-bigstack** [comment]
Thanks for the quick review @lizzy-liang-bigstack @raven-pan! 🙇‍♂️ 🙏 🫡
