### PR TITLE
292 cos header adjustments

### LINKED ISSUE #292: [Task]: COS header icon too small?
## Describe the bug

Some feedbacks of the icons is not clear? are we going to change the icon size? or resize the distance of edge.
Image

- Resize (Joy already provided)
- Hover tips  (Can we add this effect?) Optional
Image

## Version
CUBE_3.0.0_20250417-2230_02ed2ff

## To Reproduce

1. Go to Top-Right corner of 'Header'
2. Click on Icon shortcuts

## Expected behavior

User can easily understand the meaning of the icons

## Screenshots

##Additional context

### PR DESCRIPTION
**Pull request by steven-chiu-bigstack**
#### What type of PR is this?

Feat

#### What this PR does / why we need it

For `CosHeader`:

1. Update the quick access icons (Rancher and Keycloak).
2. Add hover tooltip to quick access items.
3. Refactor function bar items to support hover tooltip.

#### Which issue(s) this PR fixes

Close #292 

- UI Library

   https://github.com/user-attachments/assets/638510fe-847a-462b-a9f2-e910a493d955

- Web App

   https://github.com/user-attachments/assets/f9658239-48f8-40c6-8bb2-499f4f2f7b76

### CODE REVIEW

File: packages/cube-frontend-ui-library/src/components/CosHeader/FunctionBar.tsx [hunk 1]
```diff
@@ -1,46 +1,59 @@
...
+    Component: ComponentType<ContainerProps>
+    props: ContainerProps
+  }
 }
 
 export const FunctionBar = (props: FunctionBarProps) => {
-  const { notificationContainer, onLogout } = props
+  const { items } = props
+
+  const renderItem = (item: (typeof items)[number]) => {
```
Comment (raven-pan) [inline packages/cube-frontend-ui-library/src/components/CosHeader/FunctionBar.tsx]: We can declare type of item like this:

```tsx
const renderItem =  (item: FunctionBarItem) => { ... }
```

File: packages/cube-frontend-web-app/src/layout/Layout.tsx [hunk 2]
```diff
@@ -22,17 +22,20 @@ const integrationIcons = {
   rancher: RancherIcon,
 }
 
+const integrationTooltipMap: Record<keyof typeof integrationIcons, string> = {
```
Comment (raven-pan) [inline packages/cube-frontend-web-app/src/layout/Layout.tsx]: nitpick: Maybe we could combine `icon` and `tooltip` into single `integrationMap` like this:

```tsx
// Just for demo, feel free to rename.
const integrationMap = {
  keycloak: {
    tooltip: 'Keycloak',
    icon: KeycloakIcon,
  },
  ceph: {
    tooltip: 'Ceph',
    icon: CephIcon,
  },
  openstack: {
    tooltip: 'OpenStack',
    icon: OpenStackIcon,
  },
  rancher: {
    tooltip: 'Rancher',
    icon: RancherIcon,
  },
}

type IntegrationKey = keyof typeof integrationMap
```

**Review by raven-pan — APPROVED** [review]
Nice works!

Just a few minor nitpick, feel free to merge!

File: packages/cube-frontend-ui-library/src/components/CosHeader/FunctionBar.tsx (hunk 1 above)
Comment (steven-chiu-bigstack) [reply packages/cube-frontend-ui-library/src/components/CosHeader/FunctionBar.tsx]: You're right! I was trying out some generic type stuff and forgot to change it back.
Good catch!

File: packages/cube-frontend-web-app/src/layout/Layout.tsx (hunk 2 above)
Comment (steven-chiu-bigstack) [reply packages/cube-frontend-web-app/src/layout/Layout.tsx]: This looks much better, thanks!
