### PR TITLE
303 feat(web-app): license expiration table column wording

### LINKED ISSUE #303: [Task]: Node details - License Expiration Wording change
## Describe the bug

Image

Can we change to "License expiration" from "Expires at"?

## Version
CUBE_3.0.0_20250417-2230_02ed2ff

## To Reproduce

1. Go to 'Node detail'
2. See top

## Expected behavior
Change to "license expiration"

## Screenshots

##Additional context

### PR DESCRIPTION
**Pull request by steven-chiu-bigstack**
#### What type of PR is this?

Feat

#### What this PR does / why we need it

- Update license expiration table column wording
- Show "Unlicense" for nodes with no license installed.

#### Which issue(s) this PR fixes

Close #303

image

image

### CODE REVIEW

File: packages/cube-frontend-web-app/src/pages/node/[name]/_components/NodeSummary.tsx [hunk 1]
```diff
@@ -114,6 +114,16 @@ export const NodeSummary = (props: NodeSummaryProps) => {
     )
   }
 
+  const getLicenseExpiration = (): string => {
+    const { date } = node.license.expiry
+
+    if (!date) {
```
Comment (raven-pan) [inline packages/cube-frontend-web-app/src/pages/node/[name]/_components/NodeSummary.tsx]: Discussion:

How about using `node.license.status.current ===  NodeLicenseCurrentStatus.Unlicense` to determine whether to display the expiry for nodes?

File: packages/cube-frontend-web-app/src/utils/date.ts [hunk 2]
```diff
@@ -14,6 +14,8 @@ export const formatPanelUpdateTime = (date: Dayjs) => {
 }
 
 export const toLicenseDateDisplay = (date: string) => {
+  // TODO: i18n
+  if (!date) return 'Unlicense'
```
Comment (raven-pan) [inline packages/cube-frontend-web-app/src/utils/date.ts]: Discussion:

How about using node.license.status.current ===  NodeLicenseCurrentStatus.Unlicense to determine whether to display the expiry for nodes?

**Review by raven-pan — APPROVED** [review]
Nice works!
Just a few minor discussion, feel free to merge.

File: packages/cube-frontend-web-app/src/pages/node/[name]/_components/NodeSummary.tsx (hunk 1 above)
Comment (steven-chiu-bigstack) [reply packages/cube-frontend-web-app/src/pages/node/[name]/_components/NodeSummary.tsx]: Sure, checking the `status` property is definitely more robust than checking `expiry`. I didn’t realize we had that property, thanks for pointing it out! 🙏

File: packages/cube-frontend-web-app/src/utils/date.ts (hunk 2 above)
Comment (steven-chiu-bigstack) [reply packages/cube-frontend-web-app/src/utils/date.ts]: No problem! 👌
